"""Remove is_superuser field from user table

Revision ID: 188aa10ea7b4
Revises: e092df048ecc
Create Date: 2025-07-26 17:13:54.602360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188aa10ea7b4'
down_revision: Union[str, None] = 'e092df048ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
