"""Add user preferences and login tracking fields

Revision ID: 677646ff3366
Revises: 188aa10ea7b4
Create Date: 2025-07-26 19:07:41.408083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677646ff3366'
down_revision: Union[str, None] = '188aa10ea7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_language', sa.String(length=10), nullable=False, server_default='zh-CN'))
    op.add_column('user', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(length=45), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.String(length=10), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'timezone')
    op.drop_column('user', 'preferred_language')
    # ### end Alembic commands ###
