"""Add notification_clients table

Revision ID: 8c0a304de9c9
Revises: 677646ff3366
Create Date: 2025-07-28 09:51:00.173016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8c0a304de9c9'
down_revision: Union[str, None] = '677646ff3366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_clients',
    sa.Column('name', sa.String(length=100), nullable=False, comment='客户端名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型'),
    sa.Column('config', sqlite.JSON(), nullable=True, comment='配置信息(JSON格式)'),
    sa.Column('switches', sqlite.JSON(), nullable=True, comment='推送场景开关(JSON格式)'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('interactive', sa.Boolean(), nullable=False, comment='是否支持交互'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_clients_id'), 'notification_clients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_clients_id'), table_name='notification_clients')
    op.drop_table('notification_clients')
    # ### end Alembic commands ###
